spring:
  application:
    name: account
  profiles:
    active: ${ACTIVE:default}
  config:
    import: configserver:http://${configserver.host:localhost}:${configserver.port:8888}
  banner:
    location: classpath:banner.txt
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
server:
  port : 8081
#management:
#  info:
#    env:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,refresh
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:9000}/eureka/
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      LoanFeigngetLoanByIdString:
#        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        slowCallRateThreshold: 75
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
#      CustomerDetailBreaker:
#        minimumNumberOfCalls: 3
#        failureRateThreshold: 50
#        slowCallRateThreshold: 75
#        slowCallDurationThreshold: 2s
#        waitDurationInOpenState: 15s
#        permittedNumberOfCallsInHalfOpenState: 3
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      testRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 2s
info:
  app:
    name: Account Microservice
    description: KimHengMicroServiceBank
    version: 1.0.1