services:
  config-server:
    build:
      context: ./../../config-server
      dockerfile: Dockerfile
    image: lengkimheng/config-server:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - bank-network
  postgres:
    build:
      context: ./../../database/postgrest
      dockerfile: Dockerfile
    image: lengkimheng/postgres-db:latest
    mem_limit: 700m
    ports:
      - "5432:5432"
    networks:
      - bank-network
    environment:
      POSTGRES_USER: loan_admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: loan_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongodb:
    build:
      context: ./../../database/mongodb
      dockerfile: Dockerfile
    image: lengkimheng/account-db:latest
    mem_limit: 700m
    ports:
      - "27018:27017"
    networks:
      - bank-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: kimheng
      MONGO_INITDB_ROOT_PASSWORD: kimheng0308
    volumes:
      - mongo-data:/data/db
  loan:
    # image: lengkimheng/loan-service:1.0
    build:
      context: ./../../loan
      dockerfile: Dockerfile
    image: lengkimheng/loan-service:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - bank-network
    depends_on:
      - config-server
      - postgres
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      ACTIVE: prod
      CONFIGSERVER_HOST: config-server
      CONFIGSERVER_PORT: 8888
      EUREKA_SERVER: eureka-server
      EUREKA_PORT: 9000
  account:
    build:
      context: ./../../account
      dockerfile: Dockerfile
    image: lengkimheng/account-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    depends_on:
      - config-server
      - eureka-server
      - mongodb
    environment:
      ACTIVE: prod
      CONFIGSERVER_HOST: config-server
      CONFIGSERVER_PORT: 8888
      EUREKA_SERVER: eureka-server
      EUREKA_PORT: 9000
  eureka-server:
    build:
      context: ./../../eureka-server
      dockerfile: Dockerfile
    image: lengkimheng/eureka-server:1.0
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      ACTIVE: prod
      CONFIGSERVER_HOST: config-server
      CONFIGSERVER_PORT: 8888
      EUREKA_SERVER: eureka-server
      EUREKA_PORT: 9000
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=KimHengBanking
      - RABBITMQ_DEFAULT_PASS=KimHengBanking
    networks:
      - bank-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
networks:
  bank-network:
    driver: bridge
volumes:
  postgres-data:
  mongo-data:
  rabbitmq-data:
