spring:
  application:
    name: apigateway
  profiles:
    active: ${ACTIVE:default}
  config:
    import: configserver:http://${configserver.host:localhost}:${configserver.port:8888}
#  cloud:
#    gateway:
#      server:
#        webflux: 
#          discovery:
#            locator:
#              enabled: true		  
server:
  port: 8080