spring:
  application:
    name: apigateway
  profiles:
    active: ${ACTIVE:default}
  config:
    import: configserver:http://${configserver.host:localhost}:${configserver.port:8888}
server:
  port: 8000