spring:
  application:
    name: eureka-server
  profiles:
    active: ${ACTIVE:prod}
  config:
    import: configserver:http://${configserver.host:localhost}:${configserver.port:8888}
server:
  port: 9000