server:
  port: 8888
spring:
  application:
    name: bank-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KimHeng2111/bank-config-server
          clone-on-start: true
          default-label: main
  banner:
    location: classpath:banner.txt
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
encrypt:
  key: "lengkimheng2111LovePheary"
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"