server:
  port: 8888

spring:
  application:
    name: bank-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KimHeng2111/bank-config-server
          clone-on-start: true
          default-label: main

encrypt:
  key: "lengkimheng2111LovePheary"