spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config #Use With resoure path location
		  # file:///<path location
server:
  port: 8888